### ISSUE TITLE
Support for arbitrary messaging between Max and browser

### ISSUE THREAD

**Issue by grrrwaaa** [Cycling74/xebra.js#15]
It would be great to add some kind of support for arbitrary messaging back & forth between Max and the browser, since the websocket is already there. For example, this would be enough to add a chatroom to a multi-user scenario. 

There's an example hack given in tutorial-09-arbitrarymessages.html which after some fiddling I did manage to get working for sending strings from the browser to max, but lists etc. have to be encoded as strings and decoded at the other end (not too hard via [fromsymbol], but maybe it could be avoided). I was able to use the same hack for getting messages from Max to the browser, but this failed when trying to send multiple messages very rapidly (only the latest message in a bunch is sent). 

It seems like it would be far more useful and stable to provide an inlet and outlet to mira.frame, such that any messages in the inlet are sent to browsers, and messages received from a browser are sent from the outlet. (Or if not on mira.frame itself, on a new object, e.g. "mira.ws"?) At the browser end, there could be a XebraState.on("message", function(...) {}) to receive these generic messages from Max, and XebraState.send(...) for sending generic messages to Max. 

It would be great if this could support lists and numbers, not just single strings.

For multi-client cases, it would be great to be able to identify specific clients. Perhaps messages received in Max are prepended by a session ID, and the same session ID can be used to send messages to a specific browser client (rather than broadcast).

**Comment by fde31** [comment]
Totally agree that this would be useful. Trying to wrap my head around how to best send/receive messages in Max or on Xebra.State. If we take the mira.frame approach, would that be useful for people that ignore the patcher->frame->object hierarchy and operate on the global State instance in the browser? One use-case could be an web application sending motion data and some messages to Max. If both operate on the State directly it might make things much simpler for the developer instead of having to listen for added frames etc!? Might be that we'd like to consider it advanced anyway and it would be fine. Initially I'm a bit leaning towards a separate object, but definitely be convinced otherwise.

In general curious what @starakaj and @benbrackenc74 think here.

Mira uses a set of different ids and client names (as used in mira.multitouch, mira.status etc.) So reusing these for received messages in Max seems easy enough and definitely useful to do. I also definitely like the idea of offering broadcast alongside single-client channel messaging support.

Oh and yeah, definitely +1 on support for numbers, strings and lists.

One word on the rapid message firing: Internally we use a small buffer to limit the amount of changes being sent to client within a certain timeframe. Guess this would explain why only the last message of a bunch might get sent in a rapid fire scenario.

**Comment by starakaj** [comment]
Hey @fde31, there's a branch st/mira_channel that takes a stab at this (on both xebra-communicator and xebra.js). You'll also need to pull the latest master on the max repo, and rebuild both the mira as well as the miraweb package. That should give you a mira.channel object, which does big chunks of what this ticket hopes for. LMK what you think.

**Comment by fde31** [comment]
closed by merging pr #24
