### ISSUE TITLE
client does not respect viewmode if mira.frame is in a subpatcher

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/xebra.js#16]
On launch, "Linked" mode is default but, for subpatches set to Open In Presentation Mode and containing mira.frame, Miraweb shows Patching view until either (1) View Mode is set to Presentation or (2) Patcher containing mira.frame is taken out of then put back in to Presentation mode.

See the attached file. This is not a problem in the Mira app.

**Comment by benbrackenc74** [comment]
For an example, paste the following in a patcher, reopen and view in client:

<pre><code>
----------begin_max5_patcher----------
773.3ocwVsrjiBBEcs9UXw5LoTyiVmcy2QWcYgJZnaDr.Lc5oq9eePvGfIl9
wlYSzbtx8w4x8.u66AxYWPBPvuCdLvy6ceOOMTOf2v+8.MvKEDnP+Y.J5UV9
yfMFSRzEoFtcDokiDHpDJwLZFGUHMNO9v1vMAwoI5GGS19PZZZRh583sgAOM
rXZWClRPRcnBmAYcxknsPYwILs9FwH8twvNA6WWz.NtTWHph6WQiEiP9FAog
A1gEwGHnAFxCTgInyHtv0md.XaqErm0R5o0mYZG8vlIHL0.saBhiNiGWe7DJ
jqJdopx63l76RxQvraXkHNsCqSEC3G9iozLekrumnhh070w8g8O1mDNyUp8B
0DVwKnRKl2CvZQTLcEdzCThpfcDYVEiJE3+pyuHUG3V1qfEHGeaajBaLE2e3
XHYr7.0bbIi1mDNgsGdLbOFDo2Kz+6bwn+BJr8FKV00UzxJFEphrSjC48chb
yFhwVAPxXDWSSqifpjClawT5BVTxZW2HGWe5NqMmoL1bOeqsHx5nFqYp4WYl
.d1kskPBYXf108WfTbCThjXSKHNbxHhBUE5IQAmQHN0qwx4aXoTsIt.8JtTd
RGH6MCpOG2NtIBL0kKw0HgzESBqEtHWMfpf5xGFRyjnlVhpJb+.GIO6IRaoO
G7ERfMHg.Vill2r0AqXLnnrx11JJhGLyawOn2nlFoEsrDptVPL10fknXjc3t
VXbuYP+fIT6ObyPs177Rswc10lIGju0NL1A.N9rmVdtSHwU3hIGaWFV8uQvO
78GeYyOrAUvZZTkxZMnuPyIUyQ6hz8nnD8i3v60bhVs4Dd+lS7QcLB0Mm3gl
S3Oq4rC7+m7avb31Jdu18myyqdjsdfP8dZjCOfqUGPhJH3hWtAoe0cG99ciH
Sl7Uymu5PiMUjCKdoly5nkVmO6P8yGYQvzQspfm7sOHGzKlWlYN3JCJkbbdm
z7w12L4aIvpNsOGRFjOmN98dpsyRx9yEg92gxX4Uf5yqEW8Yw0dt9JOqecmk
W0QE4O7+GfHNxkO
-----------end_max5_patcher-----------
</code></pre>

**Comment by starakaj** [comment]
Okay, so this is a pretty wild ride, near as I can tell. The core issue is that the view doesn't exist, so there's no way for the frame to know whether it's in patching or presentation mode. Not a problem, in and of itself, since the patcher as an attribute "openinpresentation" that could be used in case there's no view with the "presentation" attribute (as is the case for an unopened subpatcher). But it _seems_ like the frame is getting added _before_ the patcher is finished initializing, so there's no "openinpresentation" parameter ready when the frame gets added.

**Comment by starakaj** [comment]
f3bdda1 addresses this. I went down a rabbit hole that touched miraweb as well, but I think this simple solution is best.
