### ISSUE TITLE
Accessing Webpages via Xebra 

### ISSUE THREAD

**Issue by jitterhorse** [Cycling74/xebra.js#35]
Hi Cassie, Hi Sam,
thanks for creating xebra. i just started to work with it and created some simple applications. now i want to access pages like instagram, google or facebook like you did in you video here: 
https://www.youtube.com/watch?v=JvKcj-a4osY
how did you manage to access the images from instagram? my approach was to start a local js-script using the greasemonkey plugin for firefox and call a connection to the miraweb websocket. i get errors due to "Content Security Policy" problems. 
Thanks in advance
jitterhorse

**Comment by catarak** [comment]
@jitterhorse this repo has been moved to the [MiraWeb repository](https://github.com/Cycling74/miraweb), feel free to refile this there if you're still having this issue!

**Comment by starakaj** [comment]
Hi @jitterhorse, sorry for the slow response, I've been on vacation. So I don't remember exactly how I did this. Basically I pasted xebra.js into the dev console on the instagram page, so that it would link to a locally running xebra.js server (basically the same as using greasemonkey, I guess). I don't remember any CORS issues, tbh. Maybe you've got a snippet you could post? But yeah, if you could do it on the new miraweb repo that would be cool. Sorry for moving things around, it's a new repo.
